### ISSUE TITLE
Trouble Converting IR to Caffe

### ISSUE THREAD

**Issue by lamdawr** [Microsoft/MMdnn#111]
Hi

Platform (like ubuntu 16.04/win10): Ubuntu 14.04

Python version: 3.6 and 2.7

Source framework with version (like Tensorflow 1.4.1 with GPU): Keras 2.1.3

Destination framework with version (like CNTK 2.3 with GPU):  Caffe

Pre-trained model path (webpath or webdisk path): 

Running scripts:

I get the following error message while trying to create the .caffemodel 

  File "caffe_model1.py", line 65
    print(n.to_proto(), file=fpb)
                            ^
SyntaxError: invalid syntax
root@xxxxxxxxxxxx:/xxx/xxx/xxx/kerastocaffe# python caffe_model1.py -w caffe_model1.npy -p caffe_model1.prototxt -m caffe_model1.caffemodel
  File "caffe_model1.py", line 65
    print(n.to_proto(), file=fpb)
                            ^
SyntaxError: invalid syntax

Thanks !

**Comment by kitstar** [comment]
could you add a line in caffe_model1.py
```python
from __future__ import print_function
```
and try if it works?

**Comment by lamdawr** [comment]
Thank you very much for the reply. 
But I got the following error after adding the line from __future__ import print_function : 

Traceback (most recent call last):
  File "caffe_model1.py", line 98, in <module>
    gen_weight(args.weight_file, args.model, args.prototxt)
  File "caffe_model1.py", line 72, in gen_weight
    net = caffe.Net(prototxt, caffe.TRAIN)
Boost.Python.ArgumentError: Python argument types in
    Net.__init__(Net, unicode, int)
did not match C++ signature:
    __init__(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
    __init__(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > network_file, int phase, int level=0, boost::python::api::object stages=None, boost::python::api::object weights=None)

**Comment by kitstar** [comment]
hi @lamdawr , Could you share some files for us to reproduce? Thanks.

**Comment by lamdawr** [comment]
Hi @kitstar , what files would you like ?

**Comment by kitstar** [comment]
The code and models of source framework would be fine.

**Comment by galli-leo** [comment]
> Traceback (most recent call last):
> File "caffe_model1.py", line 98, in 
> gen_weight(args.weight_file, args.model, args.prototxt)
> File "caffe_model1.py", line 72, in gen_weight
> net = caffe.Net(prototxt, caffe.TRAIN)
> Boost.Python.ArgumentError: Python argument types in
> Net.init(Net, unicode, int)
> did not match C++ signature:
> init(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::__cxx11::basic_string<char, std::char_traits, std::allocator >, int)
> init(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits, std::allocator > network_file, int phase, int level=0, boost::python::api::object stages=None, boost::python::api::object weights=None)

This issue can be solved by converting the filenames from unicode to string, i.e. caffe.Net(str(prototxt), caffe.TRAIN)

**Comment by kitstar** [comment]
Fixed in last commit. Thanks!

**Comment by galli-leo** [comment]
@kitstar Actually, that doesn't work, since the save method also expects a string (and not unicode).

**Comment by yorkjohn** [comment]
@galli-leo ，I think you are right. only converting the string doesnt solve my problem. in file saver.py, I have met the same issue. how did you manage it please let me know.

**Comment by yorkjohn** [comment]
model = caffe.Net(str(dump_net), str(dump_weight), caffe.TEST) worked.
