### ISSUE TITLE
IR to caffe  has an 'axis' problem  (Keras to caffe)

### ISSUE THREAD

**Issue by colacool** [Microsoft/MMdnn#244]
I have got the trained model from keras which is a h5 file. And i use command ' mmtoir' to get .jason .npy &.pb . That's ok and visualized.  But when I  use command 'mmtocode' it goes wrong. 
************************
"File "/home/cuishi/.anaconda2/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 402, in emit_Concat
    axis = axis_array.index(IR_node.get_attr('axis'))
ValueError: tuple.index(x): x not in tuple"
*************************
As i check the origin code in 'caffe_emitter.py',  I found this code in 401 in this file  ' axis_array = (2, 3, 1, 0)'   But in my jason file，I found my concat layer's axis is '-1'.  So I think it makes wrong. 
So how can I solve this?  espacially, In keras, 'concatenate' require axis='-1' .
.
![image](https://user-images.githubusercontent.com/33508870/41222461-7bbbfbd6-6d99-11e8-82b2-506992c48292.png)

**Comment by namizzz** [comment]
Hi @colacool , MMdnn IR uses 'nhwc' format while the caffe uses 'nchw' format. The 'axis : -1' means the channel axis.  Thanks for your issue. We have fixed the bug you mentioned. Try the newest code!

**Comment by IvyGongoogle** [comment]
@namizzz same error, and still not works when I use the newest code.
