### ISSUE TITLE
Converting Mxnet model "LResNet50E-IR" to caffe

### ISSUE THREAD

**Issue by xn8812** [Microsoft/MMdnn#366]
Platform (like ubuntu 16.04/win10):
ubuntu
Python version:
3
Source framework with version (like Tensorflow 1.4.1 with GPU):
mxnet
Destination framework with version (like CNTK 2.3 with GPU):
caffe
Pre-trained model path (webpath or webdisk path):
https://drive.google.com/open?id=1x0-EiYX9jMUKiq-n1Bd9OCK4fVB3a54v
Running scripts:

python3 -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d model-descr512 --inputShape 3 112 112

python3 -m mmdnn.conversion._script.IRToCode -f caffe -n model-descr512.pb -w model-descr512.npy -d caffe_resnet50.py -dw caffe_resnet50.npy

I got the following errors:

Parse file [model-descr512.pb] with binary format successfully.
CaffeEmitter has not supported operator [Constant].
minusscalar0_second
CaffeEmitter has not supported operator [Constant].
mulscalar0_second
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 122, in <module>
    _main()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 143, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 131, in gen_code
    func(current_node)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 528, in emit_Mul
    self.emit_Scale(IR_node)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 373, in emit_Scale
    self.weights_dict[IR_node.variable_name] = self.weights_dict.pop(IR_node.name)
KeyError: 'mulscalar0'

**Comment by namizzz** [comment]
Hi @xn8812 , thanks for your issue, we have fixed it!

**Comment by Jubird915** [comment]
this issue is still exists.
paste my operation log here
~/imageAI/mxnet_models$ mmconvert -sf mxnet -iw ./model-r100-ii/model-0000.params -in ./model-r100-ii/model-symbol.json --inputShape 3,112,112 -df caffe -o caffe_model-r100.caffemodel -dw caffe_model-r100.npy
/home/ubuntu/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[21:29:11] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[21:29:11] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
IR network structure is saved as [7df048bc985a492eacb5f7059f18f791.json].
IR network structure is saved as [7df048bc985a492eacb5f7059f18f791.pb].
IR weights are saved as [7df048bc985a492eacb5f7059f18f791.npy].
Parse file [7df048bc985a492eacb5f7059f18f791.pb] with binary format successfully.
CaffeEmitter has not supported operator [Constant].
minusscalar0_second
CaffeEmitter has not supported operator [Constant].
mulscalar0_second
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 143, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 131, in gen_code
    func(current_node)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 540, in emit_Mul
    self.emit_Scale(IR_node)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 381, in emit_Scale
    self.weights_dict[IR_node.variable_name] = self.weights_dict.pop(IR_node.name)
KeyError: 'mulscalar0'


the mxnet model was download from insight face GitHub

**Comment by Jubird915** [comment]
I tried the model-r100-ii.zip model from insight face GitHub,using 
**mmconvert -sf mxnet -iw ./model-r100-ii/model-0000.params -in ./model-r100-ii/model-symbol.json --inputShape 3,112,112 -df caffe -o caffe_model-r100.caffemodel -dw caffe_model-r100.npy**

but the output model report a bug as below
I1120 05:56:56.677440   254 net.cpp:1138] Copying source layer plus23 Type:Eltwise #blobs=0
I1120 05:56:56.677446   254 net.cpp:1138] Copying source layer bn1 Type:BatchNorm #blobs=3
I1120 05:56:56.677506   254 net.cpp:1138] Copying source layer bn1_scale Type:Scale #blobs=2
I1120 05:56:56.677539   254 net.cpp:1138] Copying source layer dropout0 Type:Dropout #blobs=0
I1120 05:56:56.677551   254 net.cpp:1138] Copying source layer pre_fc1 Type:InnerProduct #blobs=2
I1120 05:56:56.863742   254 net.cpp:1130] Ignoring source layer fc1
I1120 05:56:56.863796   254 net.cpp:1130] Ignoring source layer fc1_scale
Runnning forward pass on LFW images
handing 0/12000
/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py:49: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
F1120 05:56:56.927628   254 eltwise_layer.cpp:41] Check failed: bottom[i]->shape() == bottom[0]->shape() 
*** Check failure stack trace: ***
    @     0x7fd4ae3fc5cd  google::LogMessage::Fail()
    @     0x7fd4ae3fe433  google::LogMessage::SendToLog()
    @     0x7fd4ae3fc15b  google::LogMessage::Flush()
    @     0x7fd4ae3fee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd4a2e95a0d  caffe::EltwiseLayer<>::Reshape()
    @     0x7fd4b2ec711a  caffe::Layer<>::Forward()
    @     0x7fd4a2ad38eb  caffe::Net::ForwardFromTo()
    @     0x7fd4b2ea7a79  caffe::Net_ForwardFromToNoGIL()
    @     0x7fd4b2ec6f75  boost::python::objects::caller_py_function_impl<>::operator()()
    @     0x7fd4a1e725cd  boost::python::objects::function::call()
    @     0x7fd4a1e727c8  (unknown)
    @     0x7fd4a1e7a613  boost::python::handle_exception_impl()
    @     0x7fd4a1e6f999  (unknown)
    @           0x4c15bf  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4d55f3  (unknown)
    @           0x4a577e  PyObject_Call
    @           0x4bed3d  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7fd4d0305830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)

the model link https://pan.baidu.com/s/1wuRTf2YIsKt76TxFufsRNA

**Comment by Jubird915** [comment]
@namizzz I use the command convert the model success, but the output caffe model are useless.
**mmconvert -sf mxnet -iw ./model-r100-ii/model-0000.params -in ./model-r100-ii/model-symbol.json --inputShape 3,112,112 -df caffe -o caffe_model-r100.caffemodel -dw caffe_model-r100.npy**

the mxnet model is from https://pan.baidu.com/s/1wuRTf2YIsKt76TxFufsRNA
and the caffe log is pasted in the last comment

**Comment by Jubird915** [comment]
found the root cause for my issue, that the input layer dim can be changed according the preprocessed data, but the DummyData layer dim can't be changed synchronously.

so if the next layer is Eltwise layer, it will report error:
Check failed: bottom[i]->shape() == bottom[0]->shape()

**Comment by grapefruitL** [comment]
@Jubird915 hi! did you sovle the problem?
Check failed: bottom[i]->shape() == bottom[0]->shape()
