### ISSUE TITLE
Cannot convert TF Mobilenet V2 to  Caffe

### ISSUE THREAD

**Issue by monckxqq** [Microsoft/MMdnn#375]
Platform : Centos 7 

Python version : 2.7

Source framework with version :Tensorflow 1.8.0

Destination framework with version : Caffe 1.0

I use the official Pre-trained model  Mobilenet V1(http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz) and success converted to Caffe model.

But I failed converting Pre-trained model Mobilenet V2(https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz).

Got error “Check failed :  _data” after "MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D -> MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D"

Is TF Mobilenet V2 to Caffe not supportted?

**Comment by namizzz** [comment]
Hi @monckxqq ,thanks for your issue, we have fixed it !

**Comment by monckxqq** [comment]
Great ! It works now. Thanks @namizzz .
So after converted, I tested the accuracy of the two model (tensorflow model and converted Caffe model) by using my own dataset.
But It seems the predicted result is different between the two model.
Have you tested the correctness after conversion ?

**Comment by namizzz** [comment]
Hi @monckxqq ,we have test the accuracy of the conversion. There is a error(around 0.4) .We find it's because of the relu6. In the converted model code ,we use `caffe.layer.ReLU`  not `ReLU6`, because there is no implementation of relu6 in caffe. Maybe you need to add a third party caffe relu6 implementation and edit the converted code to get the accurate caffe model code. Thanks!

**Comment by monckxqq** [comment]
Hi @namizzz , I find a way to add a third party caffe relu6 implementation.

But for what you said above:
> edit the converted code

Do you mean I also need to edit the code of MMdnn?
Or should I just have a try with the relu6 implementation caffe?

**Comment by namizzz** [comment]
Hi @monckxqq , edit the converted model file code
```python
    n.MobilenetV2_Conv_Relu6 = L.ReLU(n.MobilenetV2_Conv_Conv2D_crop, in_place=True, ntop=1)
to
    n.MobilenetV2_Conv_Relu6 = L.ReLU6(n.MobilenetV2_Conv_Conv2D_crop, in_place=True, ntop=1)

```
somthing like that.

**Comment by monckxqq** [comment]
Hi @namizzz , I am not sure which is the converted model file. 
Thought you mean the converted caffe model 'prototxt' file, so I changed layer type 'ReLU' to 'ReLU6' and tried again with the relu6 implementation caffe.
The accuracy was higher. So I think this problem may be solved in this way successfully?

Anyway, I used my own tensorflow mobilenet V2 model and get extracted before conversion, as it was mentioned at https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#how-to-prepare-your-model-and-conversion-parameters .
Then I converted the extracted model to caffe model and test the accuracy.
The accuracy of caffe is still lower than tensorflow (about 6%).  

I wonder there must be something wrong with my preparation step.
I did some image preprocessing in my tensorflow graph, but they disappeared after the preparation step.
Can you show me the way to extract my own tensorflow model more specifically or give me an example? Thanks~

**Comment by monckxqq** [comment]
Well, it turns out I made some mistake in my image preprocessing step and the MMdnn works fine.
After fixing all the issues, I got totally the same result with the converted caffe model.
Thanks again! @namizzz

**Comment by pageedward** [comment]
@namizzz how do u fix this problem, i meet the same problem,if need to modify code,how?,thanks

**Comment by namizzz** [comment]
Hi @pageedward ,we have fixed it! Please use the newest version MMdnn

**Comment by pageedward** [comment]
@namizzz  i have used the newest version, but problem still here ,
mobilenetv2 is download from here:
https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz
and i used tf-api https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py
to export pb model, and use tf offcial freeze_graph.py to frreeze graph
what is your converting operations?

**Comment by namizzz** [comment]
Hi @pageedward , I use the **mobilenet_v2_1.0_224_frozen.pb**  in the mobilenet_v2_1.0_224.tgz as the file. why you choose to freeze the ckpt graph manually?

**Comment by pageedward** [comment]
because i train the model with my own data from ckpt

**Comment by pageedward** [comment]
@namizzz because i train the model with my own data from ckpt

**Comment by namizzz** [comment]
Hi @pageedward , please refer to [this ](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/caffe#step-by-step-conversion-for-debugging) . Thanks!

**Comment by pageedward** [comment]
when I do 
mmtoir -f caffe -n recognizer/recognizer.prototxt -w recognizer/recognizer.caffemodel --inputShape 224,224,3 -o recognizer/caffe_mobilenetv2
the error as followed:
mmdnn.conversion.caffe.errors.ConversionError: Layer not found: DummyData1
how do u fix it?

**Comment by pageedward** [comment]
@namizzz i have fix the problem, refer is tf 2 IR

**Comment by pageedward** [comment]
@monckxqq  'I find a way to add a third party caffe relu6 implementation.' 
how to do that?
