### ISSUE TITLE
AttributeError: 'InputLayer' object has no attribute 'inbound_nodes'

### ISSUE THREAD

**Issue by nvnnghia** [Microsoft/MMdnn#55]
I followed https://github.com/Microsoft/MMdnn/blob/master/docs/keras2cntk.md to convert  Keras "inception_v3" to CNTK. when I tried to run the second step 
`python -m mmdnn.conversion._script.convertToIR -f keras -d converted -n imagenet_inception_v3.json -w imagenet_inception_v3.h5`
 I got this error
`/home/nghia/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-01-17 16:21:50.244399: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-17 16:21:50.298185: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-17 16:21:50.298543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 660 major: 3 minor: 0 memoryClockRate(GHz): 0.8885
pciBusID: 0000:01:00.0
totalMemory: 1.45GiB freeMemory: 1.08GiB
2018-01-17 16:21:50.298561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 660, pci bus id: 0000:01:00.0, compute capability: 3.0)
Network file [imagenet_inception_v3.json] and [imagenet_inception_v3.h5] is loaded successfully.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nghia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 164, in <module>
    _main()
  File "/home/nghia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 159, in _main
    ret = _convert(args)
  File "/home/nghia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 63, in _convert
    parser = Keras2Parser(model)
  File "/home/nghia/.local/lib/python2.7/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 101, in __init__
    self.keras_graph.build()
  File "/home/nghia/.local/lib/python2.7/site-packages/mmdnn/conversion/keras/keras2_graph.py", line 47, in build
    for node in layer.inbound_nodes:
AttributeError: 'InputLayer' object has no attribute 'inbound_nodes'
`
any suggestion?

**Comment by kitstar** [comment]
Hi @nvnnghia, I tested with keras 2.1.1. What is your keras version? Thanks.

**Comment by nvnnghia** [comment]
@kitstar I test with keras 2.1.3 :smile: I will try with keras 2.1.1 Thank you

**Comment by nvnnghia** [comment]
you're right. The problem is from keras version. Thank you very much

**Comment by kitstar** [comment]
Hi @nvnnghia . fixed with keras 2.1.3

**Comment by karimhasebou** [comment]
@kitstar Am still getting this error with keras 2.1.3 ? has it  been merged into the stable branch. I have tried the master branch but its installation fails

**Comment by kitstar** [comment]
Hi @karimhasebou . The stable branch supports keras 2.1.1  and master supports 2.1.3.  You can just clone the branch and use it under cloned directory with command
```bash
$ python -m mmdnn.conversion._script.xxxxx
```
Thanks.

**Comment by kitstar** [comment]
Hi @karimhasebou, stable version updated. Sorry for the late response. Long vacation, Chinese Spring Festival.

```bash
pip install -U https://github.com/Microsoft/MMdnn/releases/download/0.1.3/mmdnn-0.1.3-py2.py3-none-any.whl
```
Thanks.
