### ISSUE TITLE
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

### ISSUE THREAD

**Issue by hot-dog** [microsoft/MMdnn#721]
Platform (like ubuntu 16.04/win10):
Ubuntu 16.04
Python version:
python 3.6
Source framework with version (like Tensorflow 1.4.1 with GPU):
pytorch 1.2.0 with GPU
torchvision 0.4.0
Destination framework with version (like CNTK 2.3 with GPU):
tensorflow 1.8.0 with GPU
Pre-trained model path (webpath or webdisk path):
local disk
Running scripts:
mmtoir -f pytorch -d mobilenet_v2 --inputShape 3,224,224 -n test_model.pth

The model was trained with 4 GPUs, and I saved the architecture and weights of the net. When I excute the scripts "mmtoir -f pytorch -d mobilenet_v2 --inputShape 3,224,224 -n test_model.pth", I encountered the error:RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu, i dont know where is worng, any advices?

**Comment by hot-dog** [comment]
Here is the whole error information:
Traceback (most recent call last):
  File "/home/xx/anaconda3/envs/py36-1/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 85, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 122, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/jit/__init__.py", line 256, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/jit/__init__.py", line 323, in forward
    out = self.inner(*trace_inputs)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 531, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xx/anaconda3/envs/py36-1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

**Comment by JohnLaMaster** [comment]
I have the same problem and I don't know who to assess what device the parameters are on. Hopefully someone responds.

**Comment by rainLiuplus** [comment]
Maybe change [this line](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/pytorch_graph.py#L118) to `dummy_input = torch.autograd.Variable(torch.randn(shape), requires_grad=False).cuda()` would help. 

Thanks!

**Comment by JINGTING92** [comment]
I have a similar problem in computing the FLOPs. The error is corrected by using **net** instead of **net.module**.

**Comment by Linus4world** [comment]
_"module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu"_

For anybody still encountering this issue:
This error often happens when the nn.Model is not passed to the GPU. Make sure to 
1) Select your desired GPU with e.g. `torch.cuda.set_device('cuda:0')` and 
2) call `model.cuda()` for your nn.Model

**Comment by yustiks** [comment]
@Linus4world it worked, thanks

**Comment by hitbuyi** [comment]
> _"module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu"_
> 
> For anybody still encountering this issue: This error often happens when the nn.Model is not passed to the GPU. Make sure to
> 
> 1. Select your desired GPU with e.g. `torch.cuda.set_device('cuda:0')` and
> 2. call `model.cuda()` for your nn.Model

What about I use CPU only?

**Comment by mmoneyy** [comment]
I have the same question ,what about just use cpu ?
